name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync project files via SFTP
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
          --exclude=".git" \
          ./ ubuntu@web.trabanino.xyz:/home/metodologias.trabanino.xyz/public_html/

      - name: Install dependencies and start server
        run: |
          ssh ubuntu@web.trabanino.xyz << 'EOF'
          cd /home/metodologias.trabanino.xyz/public_html/
          npm install
          sudo npm install -g pm2
          pm2 start server.js --name metodologias || pm2 restart metodologias
          EOF