name: Deploy to CyberPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync project files via SFTP
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
        --exclude=".git" \
        ./ ubuntu@web.trabanino.xyz:/home/metodologias.trabanino.xyz/public_html/

    - name: Install dependencies on the server
      run: |
        ssh ubuntu@web.trabanino.xyz << 'EOF'
        cd /home/metodologias.trabanino.xyz/public_html/
        npm install
        pm2 restart server.js  # Restart the Node.js app
        EOF
